### ISSUE TITLE
Challenge Required

### ISSUE THREAD

**Issue by dropitlikecross** [masokky/instagram-tools#1]
Trying to use any of the scripts results in:

> { [CheckpointError: Instagram call checkpoint for this action!]
>   json:
>    { message: 'challenge_required',
>      challenge:
>       { url: 'https://i.instagram.com/challenge/7553558416/61okq4FlHw/',
>         api_path: '/challenge/7553558416/61okq4FlHw/',
>         hide_webview_header: true,
>         lock: true,
>         logout: false,
>         native_flow: true },
>      status: 'fail',
>      error_type: 'checkpoint_challenge_required' },
>   name: 'CheckpointError',
>   message: 'Instagram call checkpoint for this action!',
>   url: 'https://i.instagram.com/challenge/7553558416/61okq4FlHw/',
>   session:
>    Session {
>      _device:
>       Device {
>         username: 'mymymymy',
>         _md5int: 317189750186453,
>         _api: 21,
>         _release: '5.1.1',
>         _dpi: '424',
>         _resolution: '1080x1920',
>         _info: [Object],
>         _language: 'en_US' },
>      _cookiesStore:
>       CookieMemoryStorage {
>         storage:
>          { idx: { 'i.instagram.com':
>    { '/':
>       { rur:
>          Cookie="rur=FRC; Path=/; Secure; HttpOnly; hostOnly=true; aAge=12ms; cAge=12ms",
>         mid:
>          Cookie="mid=XDqv3wABAAGIcuAj4uPbYQguO80y; Expires=Wed, 10 Jan 2029 03:26:23 GMT; Max-Age=315360000; Path=/; Secure; hostOnly=true; aAge=11ms; cAge=11ms",
>         mcd:
>          Cookie="mcd=3; Expires=Wed, 10 Jan 2029 03:26:23 GMT; Max-Age=315360000; Path=/; Secure; hostOnly=true; aAge=12ms; cAge=12ms",
>         csrftoken:
>          Cookie="csrftoken=aRoZXfJHTXpIMPBX2FzZmgG1EUvJ248M; Expires=Sun, 12 Jan 2020 03:26:23 GMT; Max-Age=31449600; Path=/; Secure; hostOnly=true; aAge=12ms; cAge=12ms" } } } } },
>      _jar: RequestJar { _jar: [CookieJar] } } }
> (node:3203) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

**Comment by masokky** [comment]
Temporary disable step:
1. Login to instagram through web browser
2. Go to "Edit Profile"
3. Scroll down and select "Temporary disable my account"
4. Select "Just need a break"
5. Submit
